<?php

namespace Database\Seeders;

use App\Models\CoupleSoft;
use Illuminate\Database\Seeder;

class CoupleSoftSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /// ENG
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "D", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "ENG", "type" => "Q", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);
        
        /// SPA
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "Dale a userName un buen masaje de espalda. Use un aceite aromático o alguna loción si los tiene disponibles. Aprovecha para preguntarle qué estilo de masaje le gusta más.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "D", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "SPA", "type" => "Q", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        /// RUS
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "Dale a userName un buen masaje de espalda. Use un aceite aromático o alguna loción si los tiene disponibles. Aprovecha para preguntarle qué estilo de masaje le gusta más.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "D", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "M", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);

        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "Give userName a good back massage. Use an aromatic oil or some lotion if you have them available. Take this chance to ask him what massage style he likes best.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "Gently kiss userName's hand and continue doing so as you go up his arm and neck (for the good result of this Forfeit, it is important that userName has his arm uncovered). When you reach the top of his neck, pay extra attention to the area behind his ears. You can alternate kisses and soft strokes of your lips on the hairs on his skin. You can also use your tongue sparingly.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "Allow userName to blindfold you and then ask him to place a little perfume somewhere on his body. You will have to find and identify the part of userName's body that has perfume on, using only your sense of smell and touch. If you give the wrong answer, you will have to take off a garment.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "Gently scratch userName's back and scalp for a few minutes looking for sensitive spots that give him pleasure. To enhance the experience, you can use some aromatic oil or lotion.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "Place your belly on userName's lap and let him spank you gently on your buttocks, at least 30 times. Before you start, it is important that you remind userName of an incident for which you will be punished.", "shot" => 3]);
        CoupleSoft::create(["lang" => "RUS", "type" => "Q", "gender" => "F", "value" => "With userName's back uncovered, gently kiss the area from his neck to his hips. Afterwards, do the same using your lips or a feather to gently brush the area.", "shot" => 3]);
    }
}
